# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_rawhtml', '0001_rawhtmlplugindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawhtmlplugindata',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawhtmlplugindata',
            name='body',
            field=models.TextField(verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='rawhtmlplugindata',
            name='label',
            field=models.CharField(default='', max_length=40),
        ),
    ]
