# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-10 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('djangocms_rawhtml', '0002_auto_20201210_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourColumnRawHTMLPluginData',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_rawhtml_fourcolumnrawhtmlplugindata', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(default='', max_length=40)),
                ('body_left', models.TextField(verbose_name='HTML')),
                ('body_middle_left', models.TextField(verbose_name='HTML')),
                ('body_middle_right', models.TextField(verbose_name='HTML')),
                ('body_right', models.TextField(verbose_name='HTML')),
                ('full_width', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ThreeColumnRawHTMLPluginData',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_rawhtml_threecolumnrawhtmlplugindata', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(default='', max_length=40)),
                ('body_left', models.TextField(verbose_name='HTML')),
                ('body_middle', models.TextField(verbose_name='HTML')),
                ('body_right', models.TextField(verbose_name='HTML')),
                ('full_width', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TwoColumnRawHTMLPluginData',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_rawhtml_twocolumnrawhtmlplugindata', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(default='', max_length=40)),
                ('body_left', models.TextField(verbose_name='HTML')),
                ('body_right', models.TextField(verbose_name='HTML')),
                ('full_width', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
